name: news_app_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  ionicons: ^0.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  
  cached_network_image: ^3.2.3
  flutter_hooks: ^0.18.6
  
  # ⭐⭐ ¡ACTUALIZADO PARA SER COMPATIBLE! ⭐⭐
  floor: 1.4.2
  retrofit: 4.9.1          # ← COMPATIBLE con retrofit_generator 6.x
  
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Generadores - ya compatibles entre sí
  retrofit_generator: 6.0.0+3
  floor_generator: 1.4.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300